---
# file: roles/setup/tasks/main.yml

- name: Install chocolatey and packages needed for building ptlite
  win_chocolatey:
    name:
      - chocolatey
      - chocolatey-core.extension
      - visualstudio2019community
      - putty
      - tortoisehg
      - meld
      - nodejs-lts
      - googlechrome
    state: present  